Natcam/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.conf.urls import patterns, url
from app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
      url(r'^home', views.primerRegistro, name='agregar_clientes'),

    #ASESOR



    #ASISTENTE
    url(r'^editar/primer_registro/(?P<pk>\d+)', views.PrimerRegistroEdit, name='editar_primer_registro'),
    url(r'^eliminar/(?P<pk>\d+)$', views.PrimerRegistroDelete, name='eliminar_primer_registro'),
    url(r'^clientes/', views.clientes, name='clientes'),
    url(r'^desempeno/', views.desempeno, name='desempeno'),

    url(r'^$', 'django.contrib.auth.views.login', name='login'),
    url(r'^account/', include('usuarios.urls')),


    url(r'^odc1/(?P<cliente_id>\d+)/', views.orden_compra1, name='odc1'),
    url(r'^odc2/(?P<cliente_id>\d+)/', views.orden_compra2, name='odc2'),
    url(r'^odc3/(?P<cliente_id>\d+)/', views.orden_compra3, name='odc3'),
    url(r'^segundo_registro/$', views.segundoRegistro, name='segundo_registro'),


    url(r'^editar/segundo_registro/(?P<pk>\d+)', views.SegundoRegistroEdit, name='editar_segundo_registro'),
    url(r'^eliminar/(?P<pk>\d+)$', views.SegundoRegistroDelete, name='eliminar_segundo_registro'),
    url(r'^(?P<cliente_id>\d+)$', views.enviar_email, name='enviar_email'),
    url(r'^calendario/$', views.calendario, name='calendario'),

    url(r'^calendario/mes/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/$',views.dia, name='post_detail'),

    #cargar pdfs
    url(r'^cargar_pds/(?P<id>\d+)', views.cargar_pdfs, name='cargar_pdfs'),
    url(r'^cliente/perfil/(?P<id>\d+)', views.cliente_perfil, name='cliente_perfil'),
    url(r'^gael/admin/(?P<id>\d+)', views.empleado_perfil, name='empleado_perfil'),
    url(r'^gael/admin/sucursales/', views.sucursales, name='sucursales'),
    url(r'^gael/admin/sucursal/(?P<pk>\d+)/$', views.sucursal_unica, name='sucursal_unica'),
    url(r'^gael/admin/comisiones/$', views.comisiones_admingael, name='comisiones_admingael'),

    #asistente
    url(r'^gastos_oficina/', views.gastos_oficina, name='gastos_oficina'),
    url(r'^ver_resumencom/fecha/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/$', views.ver_resumencom, name='ver_resumencom'),
]


from django.conf import settings

# ... your normal urlpatterns here
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT})


        )

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Sucursal(models.Model):
    nombre = models.CharField(max_length=50)
    direccion = models.CharField(max_length=50)
    estado = models.CharField(max_length=50)
    telefono = models.SmallIntegerField()
    color = models.CharField(max_length=6, default='#2FCC71')

    class Meta:
        verbose_name_plural = 'Sucursales'

    def __str__(self):
        return self.nombre

class GatosSucursal(models.Model):
    sucursal = models.ForeignKey(Sucursal)
    renta = models.PositiveIntegerField(null=True)
    telefono = models.PositiveIntegerField(null=True)
    luz = models.PositiveIntegerField(null=True, blank=True)
    agua = models.PositiveIntegerField(null=True, blank=True)
    varios = models.PositiveIntegerField(null=True)
    fecha = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.sucursal.nombre

PORCENTAJE_GANANCIA_CHOICES = (
    ('0', '0%'),
    ('1', '1%'),
    ('2', '2%'),
    ('3', '3%'),
    ('4', '4%'),
    ('5', '5%'),
    ('6', '6%'),
)
PERSONAL_CHOICES = (
    ('1', 'Asesor'),
    ('2', 'Asistente'),
    ('3', 'Gael'),
)

class Datos(models.Model):
    usuario = models.ForeignKey(User)
    tipo = models.CharField(max_length=2, choices=PERSONAL_CHOICES)
    porcentaje_ganancia = models.CharField(max_length=1, choices=PORCENTAJE_GANANCIA_CHOICES)
    sucursal = models.ForeignKey(Sucursal, blank=True, null=True)
    claveinterb = models.CharField('Clave Interbancaria',max_length =18)
    num_de_cuenta = models.CharField(max_length=16)
    banco = models.CharField(max_length=50)

    def __str__(self):
        return self.usuario.username

app/forms.py
# -*- encoding: utf-8 -*-
from .models import PrimerRegistro, SegundoRegistro, Order, RelacionP, CargarPdfs
from django import forms
from django.forms import ModelForm

class PrimerRegistroFORM(ModelForm):
    class Meta:
        model = PrimerRegistro
        fields = ('nombre', 'apellidos', 'calle','numero','colonia_fraccionamiento','municipio_delegacion','endidad','cp', 'nss','telefono','empresa','registro_patronal','comision','email','numero_de_cuenta','banco')
        #exclude = ['operador_que_lo_registro',]
        widgets={
            'nombre': forms.TextInput(attrs={'type':'text','required':'true','class':'form-control form-control-sm  col-md-2'}),
            'apellidos': forms.TextInput(attrs={'type':'text','required':'true','class':'form-control form-control-sm  col-md-2'}),
            'calle': forms.TextInput(attrs={'type':'text','required':'true','class':'form-control form-control-sm'}),
            'numero': forms.TextInput(attrs={'type':'text','required':'true','class':'form-control form-control-sm'}),
            'colonia_fraccionamiento': forms.TextInput(attrs={'type':'text','required':'true','class':'form-control form-control-sm'}),
            'municipio_delegacion': forms.TextInput(attrs={'type':'text','required':'true','class':'form-control form-control-sm'}),
            'endidad': forms.TextInput(attrs={'type':'text','required':'true','class':'form-control form-control-sm'}),
            'cp': forms.TextInput(attrs={'type':'text','required':'true','class':'form-control form-control-sm'}),
            'nss': forms.TextInput(attrs={'type':'text','required':'true','class':'form-control form-control-sm','min':'8', 'max':"10"}),
            'telefono': forms.TextInput(attrs={'type':'number','required':'true','class':'form-control form-control-sm','placeholder':'Lada - digitos', 'max':"9999000000"}),
            'empresa': forms.TextInput(attrs={'type':'text','required':'true','class':'form-control form-control-sm','placeholder':'Nombre de la empresa'}),
            'registro_patronal': forms.TextInput(attrs={'type':'text','required':'true','class':'form-control form-control-sm','placeholder':'Número de registro patronal'}),
            'comision': forms.TextInput(attrs={'type':'number','required':'true','class':'form-control form-control-sm','placeholder':'Ejemplo: 15000.00','max':"1500"}),
            'email': forms.EmailInput(attrs={'type':'email','required':'true','class':'form-control form-control-sm','placeholder':'ejemplo@hotmail.com'}),
            'numero_de_cuenta': forms.TextInput(attrs={'type':'number','required':'true','class':'form-control form-control-sm','placeholder':'ejemplo: 4465-5487-5986-3215', 'max':"9999999999999999"}),
            'banco': forms.TextInput(attrs={'type':'text','required':'true','class':'form-control form-control-sm'}),

        }


class SegundoRegistroForm(forms.Form):
    cliente = forms.IntegerField(widget=forms.NumberInput(attrs={'readonly':'readonly'}))
    ife = forms.FileField()
    caratula = forms.FileField()
    tarjeta_de_mejoravit = forms.FileField()
    credito = forms.IntegerField()

class OrderForm(ModelForm):
    class Meta:
        model = Order
        exclude = ('user', 'id', 'total_amount')
        fields = ('orden_compra',)

class EmailOdcsForm(forms.Form):
    to = forms.EmailField(label='Destinatario')
    comments = forms.CharField(label='Comentario',required=False, widget=forms.Textarea(attrs={'rows':'5', 'cols':'50'}))
    url_archivos = forms.URLField(widget=forms.Textarea(attrs={'rows':'5', 'cols':'50'}))
    # ord1 = forms.CharField(widget=forms.TextInput(attrs={"type":'hidden', 'value': '{{ foo.total_amount }}'}))
    # ord2 = forms.CharField(widget=forms.TextInput(attrs={"type":'hidden', 'value': '{{foo.total_amount }}'}))
    # ord3 = forms.CharField(widget=forms.TextInput(attrs={}))

class BuscarDiaForm(forms.Form):
    fecha = forms.DateField(widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}))

class PReferenciaForm(forms.Form):
    cliente = forms.IntegerField(widget=forms.NumberInput(attrs={'readonly':'readonly'}))
    ref_pago = forms.CharField(max_length=12)

class PRBoleanPagoForm(forms.Form):
    clienteb = forms.IntegerField(widget=forms.NumberInput(attrs={'readonly':'readonly'}))
    crbd_rpago = forms.BooleanField()

class OdcsPagadasForm(forms.Form):
    clientec = forms.IntegerField(widget=forms.NumberInput(attrs={'readonly':'readonly'}))
    odc1p = forms.BooleanField()
    odc2p = forms.BooleanField()
    odc3p = forms.BooleanField()


# class RelacionPFprm(ModelForm):
#     class Meta:
#         model = RelacionP
#         fields = ('fecha', 'clien

class CargarPdfsForm(ModelForm):
    class Meta:
        model = CargarPdfs
        fields = ('odc1', 'odc2', 'odc3')

class CReferenciaForm(forms.Form):
    asesor = forms.IntegerField(widget=forms.NumberInput(attrs={'readonly':'readonly'}))
    ref_p = forms.CharField(max_length=12)

class CReferenciaBoolForm(forms.Form):
    asesorb = forms.IntegerField(widget=forms.NumberInput(attrs={'readonly':'readonly'}))
    crdb_rpago = forms.BooleanField(initial=False)

app/templates/gaeladmin/resumen_dia_comision.html
{% extends "base/base-gael.html" %}




	{% block css_add %}

	<style>
	.color{
		background-color: #e74c3c;
		font-size: 4rem;
	}
	.numero{
		text-align: center;
		color: #fff;
		margin-left: 10px;
		margin-right: 10px;
	}
	.huge{
		font-size: 2rem;
	}
	.panel{
		background-color: #e74c3c;
		color: #fff;
        text-align: left;
	}
    .True{
        background-color: #00C65D;
    }
    .False{
        background-color: #e74c3c;
    }
    .naranja{
        background-color: #ff9800;
        color: #f0f0f0;
    }
	</style>

	{% endblock css_add %}

{% block contenido %}
        <div class="modal fade" id="paso2" >
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="container">
                    <div class="row">
                        <div class="col-md-2 col-sm-2">
                        </div>
                        <div class="col-md-5 col-sm-4 " >
                            <div class="text-danger mr"><h4 class="ma">Agrega Referencia de Pago1.</h4>
                            </div>
                                <form method="post"  role="form" >
                                     {% csrf_token %}
                                    {{ r_form.asesor.label }}
                                    {{ r_form.asesor }}
                                    <hr/>
                                    {{ r_form.ref_pago.label }}
                                    {{ r_form.ref_p}}
                                    <hr/>
                                    <button type="submit" class="btn btn-success" name="referencia_pago">Guardar</button>
                                    <hr>
                                </form>
                        </div>
                        <div class="col-md-4 col-sm-2"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
        <div class="modal fade" id="paso3" >
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="container">
                    <div class="row">
                        <div class="col-md-2 col-sm-2">
                        </div>
                        <div class="col-md-5 col-sm-4 " >
                            <div class="text-danger mr"><h4 class="ma">Agrega Referencia de Pago.</h4>
                            </div>
                                <form method="post"  role="form" >
                                     {% csrf_token %}
                                    {{ b_rform.asesorb.label }}
                                    {{ b_rform.asesorb }}
                                    <hr/>
                                    cheque cobrado
                                    {{ b_rform.crdb_rpago }}
                                    <hr/>
                                    <button type="submit" class="btn btn-success" name="cheque_cobrado">Guardar</button>
                                    <hr>
                                </form>
                        </div>
                        <div class="col-md-4 col-sm-2"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <table class="table">
             <thead>
              <tr>
                 <th>Fecha</th>
                 <th>Asesor</th>
                  <th>Cliente</th>
                 <th>%comision</th>
                 <th>Comision</th>
                 <th>Baucheo</th>
                 <th>Total</th>

                  <th></th>
              </tr>
             </thead>

             <tbody>
                {% for rp_c in diass %}
                        <a href="">    </a>
                        <tr>
                            <td>{{ rp_c.fecha|date:"Y/m/d" }}</td>
                            <td class="{{ rp_c.asesor }}">{{ rp_c.asesor }}</td>
                            <td>{{ rp_c.cliente.nombre }}{{ rp_c.cliente.apellidos }}</td>
                            <td>{{ rp_c.p_asesor }}</td>
                            <td>{{ rp_c.comision }}</td>
                            <td>100</td>
                            <td>{{ rp_c.com_t}}</td>
                        </tr>
                {% endfor %}
             </tbody>
            <tfoot>
                <tr class="totalColumn" >
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td class="naranja"></td>
                </tr>
            </tfoot>
            </table>


    <hr/>
<div class="row">
    <div class="col-md-7">
            <table class="table">
        <thead>
            <tr>
                <th>Asesor</th>
                <th>Total</th>
                <td>Ref. Pago</td>
                <td>Acciones</td>
            </tr>
        </thead>
        <tbody>
            {% for fi in asesoressd %}
                <tr>
                    <td>
                        {{ fi.asesor }}
                    </td>
                    <td>
                          {{ fi.comision_t }}
                    </td>
                    <td class="{{ fi.crdb_rpago }}">
                        {{ fi.ref_p }}
                    </td>
                    <td>
                        <div class="dropdown">
                            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                Asignar<span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                <li>
                                    <a  data-toggle="modal" data-target="#paso2" id="boton02">
                                        <button value="{{fi.asesor.id}}"  class="btn btn-success boton_perfil">cheque
                                        </button>
                                    </a>
                                </li>
                                <li>
                                    <a  data-toggle="modal" data-target="#paso3" id="boton03">
                                        <button  value="{{fi.asesor.id }}" class="btn btn-success boton_perfib">cheque cobrado
                                        </button>
                                    </a>
                                </li>
                              </ul>
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>
    <div class="col-md-5"></div>
</div>


    <div class="row">
        <div class="col-md-9">
        </div>
        <div class="col-md-3">
            <button type="button" class="btn btn-primary"  onClick="window.print()">generar PDF</button>
        </div>
    </div>


    {% load staticfiles %}
    <script src="{% static 'js/datatables.min.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('#hideshow').on('click', function (event) {
                $('#accordion').toggle('hide');
            });

            $('table thead th').each(function(i) {
                calculateColumn(i);
            });
            var $theButtons = $(".boton_perfil");
            var $theinput = $("#id_asesor");
            $theButtons.click(function(){
               $theinput.val(this.value);
            });
            var $theButtonsb = $(".boton_perfib");
            var $theinputb = $("#id_asesorb");
            $theButtonsb.click(function(){
               $theinputb.val(this.value);
            });
        });
        function calculateColumn(index) {
            var total = 0;
            $('table tr').each(function () {
                var value = parseInt($('td', this).eq(index).text());
                if (!isNaN(value)) {
                    total += value;
                }
            });
            $('table tfoot td').eq(index).text('Total: ' + total);
        }
    </script>
                <!-- /.row -->
{% endblock contenido %}
{% block javascript %}

{% endblock %}

app/templates/gaeladmin/sucursales.html
{% extends 'base/base-gael.html' %}

{% block contenido %}

    {% load staticfiles %}
    <script src="{% static 'js/datatables.min.js' %}"></script>

    <script type="text/javascript">
	// For demo to fit into DataTables site builder...
	$('#example')
		.removeClass( 'display' )
		.addClass('table table-striped table-bordered');
</script>


<style>
    .blanco-colore{
        color: #000000;
    }
    .blanco-color{
        color: #ffffff;
    }

    .list-group-item.active, .list-group-item.active:hover, .list-group-item.active:focus {
        z-index: 2;
        color: #ffffff;
        background-color: #ffffff;
        border-color: #ffffff;
    }
        .panel-warning>.panel-heading {
    color: #ffffff;
    background-color: #00C65D;
    }
body{
    line-height: .006;
}
.uno>.panel-heading {
    color: #ffffff;
    background-color: #CC922F;
}
.dos>.panel-heading {
    color: #ffffff;
    background-color: #997A45;
}
.tres>.panel-heading {
    color: #ffffff;
    background-color: #FF9254;
}
.cuatro>.panel-heading {
    color: #ffffff;
    background-color: #ff35a5;
}
.cinco>.panel-heading {
    color: #ffffff;
    background-color: #52c1cc;
}
</style>
    <div class="row row-offcanvas row-offcanvas-right">

        <div class="col-xs-12 col-sm-12">
          <p class="pull-right visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
          </p>
          <div class="list-group-item active">


          </div><div><p><p></div>

       <div class="row">
                   {% for sucursal in sucursales %}
                        <div class="col-xs-6 col-lg-4 col-md-4">
                          <div class="panel {{ sucursal.color}}">
                                    <div class="panel-heading">
                                        <h4 class="blanco-color">Sucursal: {{ sucursal.nombre }}</h4></div>
                                         <div class="panel-body">

                                             <!-- Modal -->
                                            <button type="button" class="btn btn-Default btn-lg" data-toggle="modal" data-target="#myModal{{ sucursal.id }}">Asesores</button>
                                             <div class="modal fade" id="myModal{{ sucursal.id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                                              <div class="modal-dialog" role="document">
                                                <div class="modal-content">
                                                  <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                                    <h4 class="modal-title" id="myModalLabel"><strong>ASESORES</strong></h4>
                                                  </div>
                                                  <div class="modal-body">
                                                      <table class="table">
                                                          <thead>
                                                            <tr>
                                                              <th><h5><strong>Nombre del Empleado</strong></h5></th>
                                                              <th><h5><strong>Perfil</strong></h5></th>
                                                            </tr>
                                                          </thead>

                                                          {% for dato in datos %}
                                                            {% if dato.get_tipo_display == 'Asesor' %}
                                                                {% if sucursal.nombre == dato.sucursal.nombre %}
                                                                    <tbody>
                                                                        <tr>
                                                                            <td><h5>{{ dato.usuario }}</h5></td>
                                                                            <td><h5><a href="{{ dato.id }}">Ver</a></h5></td>
                                                                        </tr>
                                                                    </tbody>
                                                              {% endif %}
                                                            {% endif %}
                                                          {% endfor %}
                                                      </table>
                                                  </div>
                                                  <div class="modal-footer">
                                                    <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
                                                  </div>
                                                </div>
                                              </div>
                                            </div>
                                             <hr>
                                             <!-- Modal -->


                                         <!-- Modal -->
                                            <button type="button" class="btn btn-Default btn-lg" data-toggle="modal" data-target="#myModal{{ sucursal.id }}{{ sucursal.telefono }}">Recomienda y Gana</button>
                                             <div class="modal fade" id="myModal{{ sucursal.id }}{{ sucursal.telefono }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                                              <div class="modal-dialog" role="document">
                                                <div class="modal-content">
                                                  <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                                    <h4 class="modal-title" id="myModalLabel"><strong>RECOMIENDA Y GANA</strong></h4>
                                                  </div>
                                                  <div class="modal-body">
                                                      <table class="table">
                                                          <thead>
                                                            <tr>
                                                              <th><h5><strong>Nombre del Empleado</strong></h5></th>
                                                              <th><h5><strong>Perfil</strong></h5></th>
                                                            </tr>
                                                          </thead>

                                                          {% for dato in datos %}
                                                            {% if dato.get_tipo_display == 'Asistente' %}
                                                                {% if sucursal.nombre == dato.sucursal.nombre %}
                                                                    <tbody>
                                                                        <tr>
                                                                            <td><h5>{{ dato.usuario }}</h5></td>
                                                                            <td><h5><a href="{{ dato.id }}">Ver</a></h5></td>
                                                                        </tr>
                                                                    </tbody>
                                                              {% endif %}
                                                            {% endif %}
                                                          {% endfor %}
                                                      </table>
                                                  </div>
                                                  <div class="modal-footer">
                                                    <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
                                                  </div>
                                                </div>
                                              </div>
                                            </div>
                                             <hr>
                                             <!-- Modal -->

                                            Ingresos Mes: Febrero 120000.00
                                            <hr/>
                                            Egresos Mes: Febrero 100000.00
                                            <hr/>
                                            Ganancias: 20000.00
                                            <hr/>
                                            <a class="btn btn-default" href="#" role="button">Ver Detalles &raquo;</a>
                                        </div>
                                    </div>
                            </div>
                   {% endfor %}

          </div><!--/row-->
        </div><!--/.col-xs-12.col-sm-9-->
         </div><!--/row-->
         <hr>
{% endblock %}